### ISSUE TITLE
Register PR and Issue templates

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#1]
## 🧹 Chore Description

- Register PR and Issue templates

## ✅ Tasks

- [x] chore(template): add feature template
- [x] chore(template): add gui template
- [x] chore(template): add chore template
- [x] chore(template): add infra template
- [x] chore(template): add refactor template
- [x] chore(template): add bug template
- [x] chore(template): add PR template

## 📆 Due Date

January 6th
