### ISSUE TITLE
Configure SRS and product backlog template

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#15]
## 🧹 Chore Description

- Configure documentation
   - SRS template
   - Backlog template
   - Naming convention
   - Git commit message convention

## ✅ Tasks

- [x] chore(docs): configure SRS template
- [x] chore(docs): configure product backlog template
- [x] chore(docs): configure naming convention
- [x] chore(docs): update git commit message convention

## 📆 Due Date

January 28th
