### ISSUE TITLE
Design SQL editor and register GUI resources

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#17]
## 💡 Feature Description

- Design SQL editor and register GUI resources (continuing from previous issue #12)
- Set up top app bar used on the editor screen.
> [Android > UI Guide > Add the app bar](https://developer.android.com/develop/ui/views/components/appbar)
> [Materials Symbols and Icons](https://fonts.google.com/icons)

## 📝 Details

- If possible, design with a variable layout.
- Really, don't hard code anything, please use resources.

## ✅ Tasks

- [x] chore(manifest): declare manage external storage permission
- [x] chore(manifest): set window soft input mode to adjust nothing
- [x] gui(dimen): add xsmall, small, medium, large, xlarge values
- [x] gui(string): add sample texts and sample statements
- [x] gui(icon): add app bar material icons
- [x] gui(editor): design editor activity layout

## 📆 Due Date

February 2nd
