### ISSUE TITLE
Implement raw query executor entered into SQL editor

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#18]
## 💡 Feature Description

- Implement database creation statement executor  (continuing from previous issue #17)

## 📝 Details

- Use `SQLiteDatabase` class to implement raw query executor.
- Be careful to distinguish between query statements that return data and those that do not.
- This is not necessary to follow mvvm pattern now, but you have to refactor after enough features are complete.

## ✅ Tasks

- [x] gui(editor): add SQL statement check button
- [x] build(app): add sqlite room library dependencies
- [x] feat(sqlite): add basic database helper class
- [x] feat(dbhelper): implement raw query execute fun
- [x] gui(editor): modify editor grammar check button to run button
- [x] feat(editor): connect run button to raw query executor

## 📆 Due Date

February 8th
