### ISSUE TITLE
Implement query execute result view

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#20]
## 💡 Feature Description

- Implement query result view under the editor (continuing from previous issue #18)

## 📝 Details

- Query execute result must include success or failure (non-select-statement) and return data. (for example, `Error executing query: no such table: ~` `Query executed successfully`)
- Make it clear to users the results of their query execution by looking at the results view.
- Recommend using red text for failure messages.

## ✅ Tasks

- [x] gui(editor): add query execute result display table
- [x] feat(editor): modify raw query execute fun to return cursor
- [x] feat(editor): add query result table display fun
- [x] fix(editor): modify query result text to multi line 

## 📆 Due Date

March 11th
