### ISSUE TITLE
Modify architecture pattern to mvvm

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#23]
## 🔨 Refactoring Target

- Architecture pattern (60%) Separate concerns (40%)

## 📝 Description

- Remove any unnecessary code (Don't delete it if you think it will be used in the future)
- Initially, I tried to use the mvc pattern, but changed it to the mvvm pattern for learning purposes.
- If one has too many concerns, please separate it
- Study the list below before refactoring
   - [Create ViewModels with dependencies   ](https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-factories)

## ✅ Task

- [x] refactor(*): remove unnecessary code
- [x] refactor(editor): separate editor activity to view and view model
- [x] refactor(editor): modify to handle nullable types explicitly 
- [x] refactor(editor): modify view reference way to view binding
- [x] refactor(editor): replace magic numbers and strings with explicit constants
- [x] refactor(editor): optimize layout setup, minimizing duplication
- [x] refactor(editor): utilize ui related logic

## 💻 Current Code

- There is no test code, no architecture pattern.
- Never keep SoC (Not enough time...)

## 🎯 Expected Outcome after Refactoring

- Most of problems I listed above will be solved.
