### ISSUE TITLE
Redesign query execute result table and theme 

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#25]
## 💡 Task Description

- Fix the situation that result table cut off when result text is to long

## 📝 Details

- There is very tiny error about execute result table because it is non-scroll-view issue.
- So change it to scroll view and refactor some ui related logic

## ✅ Tasks

- [x] gui(editor): add scroll view to wrap result table
- [x] feat(*): add theme default font size and padding values
- [x] refactor(editor): update font size and padding value to theme default
- [x] fix(editor): allow to use small letter 'select' to identify query
- [x] fix(util): add result display fun to react to screen width

## 📆 Due Date

March 12th
