### ISSUE TITLE
Update project backlog and modify app minimum sdk

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#29]
## 🧹 Chore Description

- Work on necessary documents after version 1.0.0 update

## ✅ Tasks

- [x] docs(readme): update to contain release version
- [x] chore(build): downgrade min sdk to 29
- [x] chore(build): add ktlint library to clean code style
- [x] chore(build): formatting current code to ktlint
- [x] docs(git): update .gitignore
- [x] docs(backlog): update backlog format to google sheet
- [x] docs(*): update convention and srs
- [x] chore(*): remove main activity 

## 📆 Due Date

March 21th
