### ISSUE TITLE
Add app default theme GUI resources

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#3]
## 💡 Task Description

- Add app default theme GUI resources

## 📝 Details

- consider app name and rename it (think of it as 4 letters long)
- create launcher icon (background, foreground image) and add resources
- add default theme palette for text, keyword, column name, etc to colors.xml
- add default dimen values (e.g. textview_height)

> [Android Developers > Develop > UI Guide > Styles and themes](https://developer.android.com/develop/ui/views/theming/themes)

## ✅ Tasks

- [x] chore(name): rename app name to SQLI 
- [x] gui(icons): add adaptive launcher icon resources
- [x] gui(colors): add default theme palette
- [x] gui(dimens): add default dimen values

## 📆 Due Date
January 8th
