### ISSUE TITLE
Add custom splash screen using jetpack library

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#33]
## 💡 Feature Description

- Add custom splash screen

## 📝 Details

- The screen should have a gray screen and the logo in the center of the screen.
- Please read below link before 
Android > Dev > [Add a splash screen](https://developer.android.com/training/wearables/apps/splash-screen)
Android > Dev > [Add a splash screen to a new app](https://developer.android.com/develop/ui/views/launch/splash-screen)

## ✅ Tasks

- [x] chore(build): set up screen splash library
- [x] gui(icon): add splash screen adaptive icon 
- [x] gui(color): add splash screen background
- [x] gui(dimen): add splash screen icon size
- [x] gui(res): add splash screen theme
- [x] gui(res); add splash screen theme drawable
- [x] chore(manifest): modify start app theme to splash theme
- [x] feat(editor): install splash screen
- [x] chore(*): run ktlint format

## 📆 Due Date

March 28th
