### ISSUE TITLE
Update gitignore and set up ktlint pre-hook to formatting

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#35]
## 🧹 Chore Description

- Add .gitignore `Build outputs` `Android Studio` `Key store files` etc and reset git cache (You have to check project run normally before clone project with other environment (other directory?)
- Set up pre-commit hook to force `ktlintFormat`
 please refer [Codersee > Ktlint with pre-commit Hook](https://codersee.com/git-hooks-kotlin-automate-ktlint-pre-commit-hook/)

## ✅ Tasks

- [x] chore(git): apply updated gitignore list
- [X] refactor(*): improve variable and method naming
- [x] chore(git): set up pre-commit hook to ktlint format

## 📆 Due Date

March 28th
