### ISSUE TITLE
Perform unit tests for the editor view model

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#37]
## ✔️ Test Description

- Perform unit tests for the editor line number generate fun 
- This is the only thing you can unit test on
[](https://developer.android.com/training/testing/local-tests)

## ✅ Tasks

- [x] chore(build): update app version name
- [x] chore(build): add mockk and espresso dependency
- [x] refactor(editor): modify line number generate fun to accept param
- [x] test(editor): add unit test code for line number
- [x] chore(build): downgrade androidx test core to 1.5.0

## 📝 Additional Notes

- Don't forget to add test workflow on `GitHub Actions` after this issue
