### ISSUE TITLE
Resolve the no tests found issue in the github action unit test

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#41]
## 🧹 Chore Description

- Resolve the `No Tests Found` issue in the GitHub Action `Android CI - Unit Test`. This issue is continuing https://github.com/Nter-developer/sql-interpreter-android/issues/39
- While the issue could potentially stem from the `./gradle test` command itself, the most likely cause is specific annotations or library version crash within the test code.
- Also, use commands like `debugUnitTest` not `test` to save testing time.
- Since the workflow is running well it's not a bug. Therefore, I'll tag it as `infra`.

## ✅ Tasks

- [x] Post procedure to solving this issue on Tech Blog [Tech Blog](https://velog.io/@nter-developer/project-sqli-trouble-shooting-1)
- [x] infra(ci/cd): modify unit test result actions file url
- [x] infra(ci/cd): modify workflows trigger

## 📆 Due Date

April 31th
