### ISSUE TITLE
Improve editor view model readability and fun call frequency

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#43]
## 🔨 Refactoring Target

- EditorViewModel.kt `activy_editor.xml` too

## 📝 Description

- Modify var name to clearly mean it's uses `readability`
- Separate concern of function `soc
- Control line number update fun call frequency `overhead`

## ✅ Tasks

- [x] refactor(editor): add live data var to encapsulate editor view model 
- [x] refactor(editor): separate statement changed fun to except handling and update
- [x] fix(editor): modify query valid fun to ignore case 

## 🎯 Expected Outcome after Refactoring

- Clear var name, more extensibility, encapsulate
