### ISSUE TITLE
Separate line number logic from editor view model

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#45]
## 🔨 Refactoring Target

- EditorViewModel.kt

## 📝 Description

- Separate line number logic from editor view model
- I think it unnecessary to editor view model contains line number logic 

## ✅ Tasks

- [x] refactor(util): add line number manager class
- [x] refactor(editor): separate line number logic to util 
- [x] refactor(editor): reduce line number update logic call
- [x] refactor(editor): separate render fun to after text changed fun

## 🎯 Expected Outcome after Refactoring

- ensure `SoC` of editor view model
