### ISSUE TITLE
Specify project license and update release note

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#48]
## 🧹 Chore Description

- Specify project license and update release note

## ✅ Tasks

- [x] chore(readme): specify project license to mit
- [x] chore(readme): separate coc from readme.md 
- [x] chore(readme): update latest release note

## 📆 Due Date

April 23th
