### ISSUE TITLE
Add application Jetpack Compose

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#5]
## 🧹 Chore Description

- Modify the existing `build.gradle` to enable Compose.

## ✅ Tasks

- [x] chore(build): add buildFeatures and composeOptions configuration
- [x] chore(compiler): update kotilin version to 1.8.10
- [x] chore(build): add Compose BOM library dependencies

## 📆 Due Date

January 11th
