### ISSUE TITLE
Apply coroutine to asynchronous execution of database

### ISSUE THREAD

**Issue by dev-ant** [Nter-developer/sql-interpreter-android#51]
## 🔨 Refactoring Target

- Everything need asynchronous execution

## 📝 Description

- You need to update some library version and add coroutine
- Please study [introduction-coroutines](https://developer.android.com/codelabs/basic-android-kotlin-training-introduction-coroutines?hl=ko#1) before use coroutine

## ✅ Tasks

- [x] chore(build): migration groovy to kotlin DSL
- [x] chore(build): update dependencies to latest version
- [x] chore(build): add coroutine dependency
- [x] refactor(editor): asynchronize execute statement fun

## 🎯 Expected Outcome after Refactoring

- Ensure Asynchronous execution safety
