### ISSUE TITLE
Implement query editor and line counter

### ISSUE THREAD

**Issue by Nter-developer** [Nter-developer/sql-interpreter-android#9]
## 💡 Feature Description

- Implement query editing feature

## 📝 Details

- User can edit .sqlite format file 
- On the left side of screen, there is line counter

## ✅ Tasks

- [x] feat(editor): add query editor activity and layout
- [x] gui(dimen): add default padding values
- [x] gui(editor): design query editor layout
- [x] chore(manifest): modify launch activity to editor activity
- [x] feat(editor): add model view presenter about query editor 
- [x] feat(statement): add constant value of SQLite keywords
- [x] feat(editor): implement left side line counter 

## 📆 Due Date

January 15th
